// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleUSER  UserRole = "USER"
	UserRoleADMIN UserRole = "ADMIN"
	UserRoleAGENT UserRole = "AGENT"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusPendingApproval UserStatus = "pending_approval"
	UserStatusApproved        UserStatus = "approved"
	UserStatusNone            UserStatus = "none"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type User struct {
	ID               int64              `json:"id"`
	FullName         string             `json:"full_name"`
	Email            string             `json:"email"`
	Age              pgtype.Int4        `json:"age"`
	Phone            pgtype.Text        `json:"phone"`
	DateOfBirth      pgtype.Text        `json:"date_of_birth"`
	Country          pgtype.Text        `json:"country"`
	State            pgtype.Text        `json:"state"`
	School           pgtype.Text        `json:"school"`
	ProfileCompleted pgtype.Bool        `json:"profile_completed"`
	Status           UserStatus         `json:"status"`
	Password         string             `json:"password"`
	Role             UserRole           `json:"role"`
	AdminCode        pgtype.Text        `json:"admin_code"`
	Department       pgtype.Text        `json:"department"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastLogin        pgtype.Timestamp   `json:"last_login"`
	UpdatedAt        pgtype.Timestamp   `json:"updated_at"`
}
