// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO users (
  full_name,
  email,
  password,
  role,
  admin_code,
  phone
)
VALUES ($1, $2, $3, 'ADMIN', $4, $5)
RETURNING id, full_name, email, age, phone, date_of_birth, country, state, school, profile_completed, status, password, role, admin_code, department, created_at, last_login, updated_at
`

type CreateAdminParams struct {
	FullName  string      `json:"full_name"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	AdminCode pgtype.Text `json:"admin_code"`
	Phone     pgtype.Text `json:"phone"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.FullName,
		arg.Email,
		arg.Password,
		arg.AdminCode,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Age,
		&i.Phone,
		&i.DateOfBirth,
		&i.Country,
		&i.State,
		&i.School,
		&i.ProfileCompleted,
		&i.Status,
		&i.Password,
		&i.Role,
		&i.AdminCode,
		&i.Department,
		&i.CreatedAt,
		&i.LastLogin,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  full_name,
  email,
  password,
  phone
)
VALUES ($1, $2, $3, $4)
RETURNING id, full_name, email, age, phone, date_of_birth, country, state, school, profile_completed, status, password, role, admin_code, department, created_at, last_login, updated_at
`

type CreateUserParams struct {
	FullName string      `json:"full_name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.Password,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Age,
		&i.Phone,
		&i.DateOfBirth,
		&i.Country,
		&i.State,
		&i.School,
		&i.ProfileCompleted,
		&i.Status,
		&i.Password,
		&i.Role,
		&i.AdminCode,
		&i.Department,
		&i.CreatedAt,
		&i.LastLogin,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, age, phone, date_of_birth, country, state, school, profile_completed, status, password, role, admin_code, department, created_at, last_login, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Age,
		&i.Phone,
		&i.DateOfBirth,
		&i.Country,
		&i.State,
		&i.School,
		&i.ProfileCompleted,
		&i.Status,
		&i.Password,
		&i.Role,
		&i.AdminCode,
		&i.Department,
		&i.CreatedAt,
		&i.LastLogin,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, email, age, phone, date_of_birth, country, state, school, profile_completed, status, password, role, admin_code, department, created_at, last_login, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Age,
		&i.Phone,
		&i.DateOfBirth,
		&i.Country,
		&i.State,
		&i.School,
		&i.ProfileCompleted,
		&i.Status,
		&i.Password,
		&i.Role,
		&i.AdminCode,
		&i.Department,
		&i.CreatedAt,
		&i.LastLogin,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, email, age, phone, date_of_birth, country, state, school, profile_completed, status, password, role, admin_code, department, created_at, last_login, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Age,
			&i.Phone,
			&i.DateOfBirth,
			&i.Country,
			&i.State,
			&i.School,
			&i.ProfileCompleted,
			&i.Status,
			&i.Password,
			&i.Role,
			&i.AdminCode,
			&i.Department,
			&i.CreatedAt,
			&i.LastLogin,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminFields = `-- name: UpdateAdminFields :one
UPDATE users
SET admin_code = $2,
    phone = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, full_name, email, age, phone, date_of_birth, country, state, school, profile_completed, status, password, role, admin_code, department, created_at, last_login, updated_at
`

type UpdateAdminFieldsParams struct {
	ID        int64       `json:"id"`
	AdminCode pgtype.Text `json:"admin_code"`
	Phone     pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateAdminFields(ctx context.Context, arg UpdateAdminFieldsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAdminFields, arg.ID, arg.AdminCode, arg.Phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Age,
		&i.Phone,
		&i.DateOfBirth,
		&i.Country,
		&i.State,
		&i.School,
		&i.ProfileCompleted,
		&i.Status,
		&i.Password,
		&i.Role,
		&i.AdminCode,
		&i.Department,
		&i.CreatedAt,
		&i.LastLogin,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :one
UPDATE users
SET last_login = now()
WHERE id = $1
RETURNING id, full_name, email, age, phone, date_of_birth, country, state, school, profile_completed, status, password, role, admin_code, department, created_at, last_login, updated_at
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, updateLastLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Age,
		&i.Phone,
		&i.DateOfBirth,
		&i.Country,
		&i.State,
		&i.School,
		&i.ProfileCompleted,
		&i.Status,
		&i.Password,
		&i.Role,
		&i.AdminCode,
		&i.Department,
		&i.CreatedAt,
		&i.LastLogin,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, full_name, email, age, phone, date_of_birth, country, state, school, profile_completed, status, password, role, admin_code, department, created_at, last_login, updated_at
`

type UpdateUserPasswordParams struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Age,
		&i.Phone,
		&i.DateOfBirth,
		&i.Country,
		&i.State,
		&i.School,
		&i.ProfileCompleted,
		&i.Status,
		&i.Password,
		&i.Role,
		&i.AdminCode,
		&i.Department,
		&i.CreatedAt,
		&i.LastLogin,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, full_name, email, age, phone, date_of_birth, country, state, school, profile_completed, status, password, role, admin_code, department, created_at, last_login, updated_at
`

type UpdateUserRoleParams struct {
	ID   int64    `json:"id"`
	Role UserRole `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Age,
		&i.Phone,
		&i.DateOfBirth,
		&i.Country,
		&i.State,
		&i.School,
		&i.ProfileCompleted,
		&i.Status,
		&i.Password,
		&i.Role,
		&i.AdminCode,
		&i.Department,
		&i.CreatedAt,
		&i.LastLogin,
		&i.UpdatedAt,
	)
	return i, err
}
